# Generated by Django 4.1.7 on 2023-04-26 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0002_remove_task_daystoimplement_remove_task_language_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="difficulty",
            field=models.IntegerField(),
        ),
    ]
